import type { Metadata } from "next";
import { Pacifico } from "next/font/google";
import "./globals.css";
import{AppSidebar} from "./component/Layout/Navbar"
import { SidebarTrigger,SidebarProvider} from "@/components/ui/sidebar";
import Fotter from "./component/Layout/Fotter";


const geistSans = Pacifico({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-geist-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased flex min-h-screen`}
      >
      <SidebarProvider>
          <div className="flex flex-1">
            <AppSidebar />
            <div className="flex flex-col flex-1">
              <main className="flex-1 p-10">
                {children}
                <SidebarTrigger />
              </main>
              <Fotter /> 
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
